# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_distance <- function(l, m, N) {
    .Call(`_FastGP_rcpp_distance`, l, m, N)
}

durbin <- function(r, N) {
    .Call(`_FastGP_durbin`, r, N)
}

trench <- function(r, y, N) {
    .Call(`_FastGP_trench`, r, y, N)
}

rcppeigen_invert_matrix <- function(A) {
    .Call(`_FastGP_rcppeigen_invert_matrix`, A)
}

rcppeigen_get_diag <- function(A) {
    .Call(`_FastGP_rcppeigen_get_diag`, A)
}

rcppeigen_get_det <- function(A) {
    .Call(`_FastGP_rcppeigen_get_det`, A)
}

rcppeigen_get_chol <- function(A) {
    .Call(`_FastGP_rcppeigen_get_chol`, A)
}

rcppeigen_get_chol_stable <- function(A) {
    .Call(`_FastGP_rcppeigen_get_chol_stable`, A)
}

rcppeigen_get_chol_diag <- function(A) {
    .Call(`_FastGP_rcppeigen_get_chol_diag`, A)
}

